### ISSUE TITLE
Implement a better split/glued name recognition algorithm to handle extra or missing blanks in a street or locality name

### ISSUE THREAD

**Issue by mraross** [bcgov/ols-geocoder#208] opened 2021-01-28 19:57 UTC
Another way to deal with split or combined street and locality names is to condense (e.g., remove all blanks from)  both reference and input street and locality names and use the condensed form of the name when doing full name comparisons.

|Reference Name| Name to match|Condensed reference name|Condensed name to match|
|---|---|---|---|
|sea view|sea view|seaview|seaview
|sea view|seaview|seaview|seaview
|seaview|sea view|seaview|seaview
|seaview|seaview|seaview|seaview

In the above table, regardless of the spaces in the reference name or name to match, the condensed versions are identical. This approach requires generating a condensed version of reference street and locality names during data prep as well as condensing input names during request processing.

One obvious limitation is there will be some words that are embedded in a compound word but don't appear on their own in other street or locality names. This could be handled by two dictionaries:

1. A symmetric difference dictionary that contains words that are in the street name word list but not in the locality name word list and vice-versa.

2.   a supplementary name word dictionary that is manually maintained by the geocoder administrator.

**Comment by mraross** [comment] 2021-07-01 07:46
The Familiarity Conjecture states that every compound word in a name contains a known name word as a prefix, a suffix or both.
The corollary of the Familiarity Conjecture is that a compound word split is only valid if at least one of the resulting words is a known name word

Seaview contains known word sea as a prefix and view as a suffix.
Hillside contains known word hill as a prefix.
Cedarhill contains known word hill as a suffix.
Happyvalley contains known word valley as a suffix.
Horseshoe contains known word horse as a prefix and shoe as a suffix
Horsefly contains known word horse as a prefix and fly as a suffix
Horseshoebay contains known word horse as a prefix and bay as a suffix

Horses Hoe is an invalid split of Horseshoe because no resulting word is a known name word.
Horse Shoe is a valid split because at least one of the resulting words is a known name word; in fact both horse and shoe are known.
Horseshoe bay is a valid split; horses hoebay is invalid

Can we limit splitting of compound words to a single split?

**Comment by BK01** [comment] 2022-04-06 22:20
Handling of split and glued street names was validated with 4.2.0-SNAPHOT using atp tests 178 and 451.

**Comment by BK01** [comment] 2022-04-06 22:23
Handling of glued locality name not successful in 4.2.0-SNAPSHOT (geocodertst.api.gov.bc.ca) using atp test 170. 
"206 E 15th St, Northvancouver, BC"

Additional test to validate split locality name will need to be added to atp next.

**Comment by cmhodgson** [comment] 2022-04-07 00:54
I investigated the NorthVancouver issue... the problem is with the fact that the "north" in "north vancouver" (original 2 words) is converted to the short form "N" before the compound word logic gets to handle it. I think there would be a similar issue for any multi-word street name or locality where some of the words had abbreviations. The "westKelowna" example above only succeeds because "2877 bentley" is enough information to deduce the address, it doesn't successfully split the locality into "west kelowna". I'm not sure how much of an issue this is, as I think that most words with abbreviations, certainly including directionals, are not usually part of compound words.

This fix was specifically focused on cases where the user might not know whether a given string of words was a compound word or multiple individual words, eg. "searidge" vs. "sea ridge", which both exist as street names in BC. The problem of missing or extra space characters is really much trickier to handle in a grammar-based parser. It is almost like we need an initial n-gram-based multi-word spell-correction pre-process before we try to apply the grammar.

Many of the above propose test cases for split locality names are also not what was intended to be handled by this improvement - it is intended only to deal with compound words, where the individual words themselves are found elsewhere in the vocabulary of the geocoder. Thus "Camp Bell" and "whale town" are examples we expect this improvement to handle, but "Kaml oops" is not, because "Kaml" and probably also "oops" are not words in any other street name or locality in bc, thus not known vocabulary words. These are still valid test cases, but there are is currently no plan for how to handle them - there may or may not already be ticket for this type of problem (misplaced space character).

It is also worth noting that this fix was never intended (at least in my mind, the way it was designed) to work with street directionals (eg. WestBroadway), street Types (eg. mainStreet), or street qualifiers (eg. johnsonStreetBridge) but perhaps we should have thought about these cases as well - but again, I don't think anyone ever intentionally combines these words or is unsure whether or not there is a space between them.

**Comment by BK01** [comment] 2022-04-07 16:48
Validated in Geocoder 4.2.0-SNAPSHOT based on intended scope of enhancement.

**Comment by alixcote** [comment] 2024-03-22 20:12
This is complete. Closing.

**Closed by alixcote** 2024-03-22 20:12 UTC
Labels: enhancement, api, geocoder parser, geocoder, high priority
