### ISSUE TITLE
Too many municipality locations for Langley and North Vancouver

### ISSUE THREAD

**Issue by cmhodgson** [bcgov/ols-geocoder#92] opened 2020-05-08 00:39 UTC
When you query the geocoder for langley or north vancouver, the autocomplete shows two exact matches (as expected, for each match of city and district municipality) as well as one additional match for the district municipality which returns a relatively poor location.

Possibly the GNIS location for the district munis is too far from the point we have, and causes the matching to fail, causing there to be too many muni matches returned.

**Comment by cmhodgson** [comment] 2020-05-08 00:46
Do we just need some special code to handle matching up these particular munis?

**Comment by gleeming** [comment] 2020-05-08 23:20
For these munis, there is custom logic in the prep scripts to geographically split the single Langley and North Vancouver ITN locality polygons into two to represent the separate City and District Municipality portions.  I believe that the city part is keeping the original name and to disambiguate, the DM part is being renamed to Township of Langley / District of North Vancouver.

The prep script uses the BCGNIS point coordinates to represent an ITN locality position (in lieu of a gross centroid) if the BCGNIS location falls within the polygon and the names match.  While BCGNIS does have separate records for the city and DM munis, they have the same name (just Langley and North Vancouver). Since the targeted renaming is being done before the overlay, the new DM names with additional prepended text don't match to the BCGNIS name, creating the 3rd geocoder locality entry for each case.  This is also why there is a poor location for the two DMs -- they are just the centroid of the split up ITN polygon.

The solution may be as simple as renaming the two specific BCGNIS DM records.  If they look like our desired output "Township of Langley" and "District of North Vancouver" strings before the comparison then the result should have the desired effect.

**Comment by gleeming** [comment] 2020-05-12 05:01
Updated and committed a new script to GOGS.

The BCGNIS inputs are now linked to the custom city split polygons that are already being used to divide up these two ITN localities.  As a result the locality candidate inputs are all getting consistent (re)names, and properly link to each other for the Langley and North Vancouver variants.

**Comment by BK01** [comment] 2020-05-12 15:29
Deployed the script in the DataBC environment with updated parameter values. The script was run successfully on the evening of May 11. As expected, the log entry confirmed that the new localities and locality mapping counts were reduced by 2x.

**Comment by mraross** [comment] 2020-05-21 22:31
May-2020 data verified in delivery

**Closed** 2020-11-04 07:56 UTC
Labels: data prep scripts
