### ISSUE TITLE
Better handling of different sources of street names within and as output from the geocoder.

### ISSUE THREAD

**Issue by gleeming** [bcgov/ols-geocoder#193] opened 2021-01-08 23:34 UTC
Until the python word splitting logic was recently added as per #15, the geocoder always returned actual street names from ITN.  For civic/unit/site matches, the response always outputs the official (primary) name.  An alias can be returned for a street level match, as this level of precision doesn't distinguish between name types for a street locality centroid.

With the introduction of generated aliases to assist with input interpretation (e.g. glued words), non-ITN names have been added into the set of street locality centroids.  While the official name is still retuned for civic/unit/site responses, generated names can be returned for street level matches.  As a result cases like Alex And Ria Way, West Kelowna, BC and Duns Muir Viaduct, Vancouver, BC are currently street precision return values from the silver release that are less than desirable.

It would be useful to continue to use these split word aliases for parsing inputs, but at the same time never allow them to be returned as a valid response.  An option to accommodate this would be to extend the street name objects with a flag that distinguishes actual ITN names from generated names.  This would require modifications to the FME JSON scripts as well as changes within the geocoder/BAARG to accept the extended structure and also to never allow an output of a generated split name.

A further extension of this concept could be to add a 3rd flag value for generic ITN names (e.g. lowercased cases) such as turning lane and pullout.  Then the geocoder intersection enhancement from #192 could work directly from this flag instead of internally needing to interpret ITN names.

**Comment by mraross** [comment] 2021-01-16 01:42
I think the Location Services team has to determine if the current method of splitting words in reference street names handle enough user input cases correctly to make up for the confusion caused by introducing non-official street names into autocompletion. If not we might have to back out of the current approach and solve glueing/splitting another day.

**Comment by cmhodgson** [comment] 2021-01-18 16:20
In order to support this decision, is it possible to modify the script to output a table of the new aliases it is creating? eg. Alexandra to Alex and Ria, etc. This could also help to understand this issues and possibly come up with a better a solution.

**Comment by mraross** [comment] 2021-07-24 02:13
Is being handled by #208

**Comment by alixcote** [comment] 2024-03-22 20:11
Handled by #208. Closing.

**Closed by alixcote** 2024-03-22 20:11 UTC
