### ISSUE TITLE
Separate unit numbers attached to unit designators

### ISSUE THREAD

**Issue by bstratto** [bcgov/ols-geocoder#81] opened 2020-04-23 23:46 UTC
The MSP address file has 981 addresses where the unit is a penthouse and the unit number format is PH<number or letter> (no space between PH and the remainder of the number).

These numbers are correct, and are as found in the BC Assessment address data which is known to the Geocoder. 

The geocoder deducts 33 points from the score with an UNRECOGNIZED.notAllowed penalty.

Could the geocoder not deduct the penalty since the unit number is in fact correct?

Examples:
PHC 630 ROCHE POINT DR, NORTH VANCOUVER, BC
PH9 1163 THE HIGH ST, COQUITLAM, BC

**Comment by mraross** [comment] 2020-04-24 07:46
Separate unit numbers stuck to unit descriptors. Here's some examples:

Input | Output
------- | ---------
PHC 630 ROCHE POINT DR, NORTH VANCOUVER, BC | PH C 630 Roche Point Dr, North Vancouver, BC
PH9 1163 THE HIGH ST, COQUITLAM, BC | PH 9 1163 The High St, Coquitlam, BC

**Comment by mraross** [comment] 2020-04-24 08:16
duplicate of issue #13

**Closed by mraross** 2020-04-24 08:16 UTC
Labels: enhancement, estimate needed, geocoder, geocoder parser, medium priority
